=== aleksandardikic/istGit/adresarDTD.dtd
<!ELEMENT Adresar (Osoba+,Kompanija+)>
  <!ELEMENT Osoba (ime,prezime+,datumRodjenja,adresa,brojTelefona,eMail+)>
    <!ELEMENT ime (#PCDATA)>
    <!ELEMENT prezime (#PCDATA)>
    <!ELEMENT datumRodjenja (dan,mesec,godina)>
      <!ELEMENT dan (#PCDATA)>
      <!ELEMENT mesec (#PCDATA)>
      <!ELEMENT godina (#PCDATA)>
    <!ELEMENT adresa (ulica,broj,grad,drzava?)>
      <!ATTLIST adresa tipAdrese (privremena|stalna) "privremena">
      <!ELEMENT ulica (#PCDATA)>
      <!ELEMENT broj (#PCDATA)>
      <!ELEMENT grad (#PCDATA)>
      <!ELEMENT drzava (#PCDATA)>
    <!ELEMENT brojTelefona (#PCDATA)>
      <!ATTLIST brojTelefona tipTelefona (moblini|fiksni) #REQUIRED>
    <!ELEMENT eMail (#PCDATA)>
      <!ATTLIST eMail tipEmail (privatni|sluzbeni) #REQUIRED>
<!ELEMENT Kompanija (naziv,adresa,brojTelefona,eMail+)>
  <!ELEMENT naziv (#PCDATA)>

=== aleksandardikic/istGit/Zadatak2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Adresar SYSTEM "adresarDTD.dtd">
<Adresar>
  <Osoba>
    <ime>
      Aleksandar
    </ime>
    <prezime>
      Dikic
    </prezime>
    <datumRodjenja>
      <dan>
        11
      </dan>
      <mesec>
        04
      </mesec>
      <godina>
        1997
      </godina>
   </datumRodjenja>
   <adresa tip='privremena'>
      <ulica>
          Sutjeska
      </ulica>
      <broj>
          324
      </broj>
      <grad>
          Beograd
      </grad>
      <drzava>
          Srbija
      </drzava>      
   </adresa>
   <brojTelefona tip='moblini'>
        0654622751
   </brojTelefona>
   <eMail tip='sluzbeni'>
      aleksandardikic97@gmail.com
   </eMail>   
  </Osoba>

  <Osoba>
    <ime>
      Jovan
    </ime>
    <prezime>
      Jovanovic
    </prezime>
    <datumRodjenja>
      <dan>
        21
      </dan>
      <mesec>
        06
      </mesec>
      <godina>
        1990
      </godina>
    </datumRodjenja>
    <adresa tip='privremena'>
      <ulica>
        Sutjeska
      </ulica>
      <broj>
        324
      </broj>
      <grad>
        Beograd
      </grad>
      <drzava>
        Srbija
      </drzava>
    </adresa>
    <brojTelefona tip='moblini'>
      0654665467
    </brojTelefona>
    <eMail tip='sluzbeni'>
      jjovanovic97@gmail.com
    </eMail>
  </Osoba>

  <Kompanija>
    <naziv>
      Speedy korporacija
    </naziv>
    <adresa>
     <ulica>
          Francuska
     </ulica>
     <broj>
          13
     </broj>
     <grad>
          Beograd
     </grad>
     <drzava>
          Srbija
     </drzava>      
   </adresa>
   <brojTelefona tip='fiksni'>
        011/521532
   </brojTelefona>
   <eMail tip='sluzbeni'>
      kompanija@speedy.com
   </eMail>   
  </Kompanija>
  
</Adresar>

=== aleksandardikic/istGit/Zadatak1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE adresarDTD SYSTEM "adresarDTD.dtd">
<Adresar xmlns='www.viserStudent.rs/nrt3316' >
  <Osoba>
    <ime>
      Aleksandar
    </ime>
    <prezime>
      Dikic
    </prezime>
    <datumRodjenja>
      <dan>
        11
      </dan>
      <mesec>
        04
      </mesec>
      <godina>
        1997
      </godina>
   </datumRodjenja>
   <adresa tip='privremena'>
      <ulica>
          Sutjeska
      </ulica>
      <broj>
          324
      </broj>
      <grad>
          Beograd
      </grad>
      <drzava>
          Srbija
      </drzava>      
   </adresa>
   <brojTelefona tip='moblini'>
        0654622751
   </brojTelefona>
   <eMail tip='sluzbeni'>
      aleksandardikic97@gmail.com
   </eMail>   
  </Osoba>

  <Kompanija>
    <naziv>
      Speedy korporacija
    </naziv>
    <adresa>
     <ulica>
          Francuska
     </ulica>
     <broj>
          13
     </broj>
     <grad>
          Beograd
     </grad>
     <drzava>
          Srbija
     </drzava>      
   </adresa>
   <brojTelefona tip='fiksni'>
        011/521532
   </brojTelefona>
   <eMail tip='sluzbeni'>
      kompanija@speedy.com
   </eMail>   
  </Kompanija>
  
</Adresar>

=== aleksandardikic/istGit/Adresar.xml
<?xmlversion ="1.0" encoding="utf-8"?>
 <!-- <?xml-stylesheet href="xslFajl.xslt"?>-->
  <!DOCTYPE Adresar SYSTEM "adresarDTD.dtd">

  <Adresar
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Osoba idOsoba="o1">
     <punoIme>
      <ime>Aleksandar</ime>
      <srednjeIme>Slavko</srednjeIme>
      <prezime>Dikic</prezime>
      </punoIme> 
      <datumRodjenja>
        <dan>11</dan>
          <mesec>4</mesec>
        <godina>1997</godina>
     </datumRodjenja>
     <adresa tipAdrese='privremena'>
        <ulica>Sutjeska</ulica>
        <broj>324</broj>
        <grad>Beograd</grad>
        <drzava>Srbija</drzava>      
     </adresa>
     <brojTelefona tipTelefona='moblini'>0654647131</brojTelefona>
     <eMail tipEmail='sluzbeni'>aleks1@gmail.com</eMail>
      <eMail tipEmail='sluzbeni'>aleks2@gmail.com</eMail>
      <eMail tipEmail='sluzbeni'>aleks3@gmail.com</eMail>
    </Osoba>

    <Osoba idOsoba='o2'>
      <punoIme>
        <ime>Marko</ime>
        <prezime>Markovic</prezime>
       </punoIme>
      <datumRodjenja>
        <dan>20</dan>
        <mesec>3</mesec>
        <godina>1992</godina>
      </datumRodjenja>
      <adresa tipAdrese='stalna'>
        <ulica>Susag</ulica>
        <broj>21</broj>
        <grad>Beograd</grad>
        <drzava>Srbija</drzava>
      </adresa>
      <brojTelefona tipTelefona='moblini'>
        0654647131
      </brojTelefona>
      <eMail tipEmail='sluzbeni'>
        asalic97@gmail.com
      </eMail>
    </Osoba>

    <Osoba idOsoba='o3'>
      <punoIme>
        <ime>Pera</ime>
        <prezime>Peric</prezime>
      </punoIme>
      <datumRodjenja>
        <dan>20</dan>
        <mesec>3</mesec>
        <godina>2009</godina>
      </datumRodjenja>
      <adresa>
        <ulica>Susag</ulica>
        <broj>21</broj>
        <grad>Beograd</grad>
        <drzava>Srbija</drzava>
      </adresa>
      <brojTelefona tipTelefona='moblini'>
        0654647131
      </brojTelefona>
      <eMail tipEmail='sluzbeni'>
        asalic97@gmail.com
      </eMail>
    </Osoba>
    
    
    <Kompanija idKompanija='k1'>
      <naziv>Speedy korporacija</naziv>
      <adresa tipAdrese='stalna'>
       <ulica>Francuska</ulica>
       <broj>13</broj>
       <grad>Beograd</grad>
       <drzava>Srbija</drzava>      
     </adresa>
     <brojTelefona tipTelefona='fiksni'>011/521532</brojTelefona>
     <eMail tipEmail='sluzbeni'>kompanija@speedy.com</eMail>   
    </Kompanija>

   

    <Kompanija idKompanija='k2'>
      <naziv>Speedy korporacija druga</naziv>
      <adresa>
        <ulica>Makedonska</ulica>
        <broj>54</broj>
        <grad>Beograd</grad>
        <drzava>Srbija</drzava>
      </adresa>
      <brojTelefona tipTelefona='fiksni'>011/521321</brojTelefona>
      <eMail tipEmail='sluzbeni'>kompanija@speedy.com</eMail>
      <eMail tipEmail='sluzbeni'>kompanija@speedy.com</eMail>
      <eMail tipEmail='sluzbeni'>kompanija@speedy.com</eMail>
    </Kompanija>

    <Kompanija idKompanija='k3'>
      <naziv>Kompanija 3</naziv>
      <adresa>
        <ulica>Ulica</ulica>
        <broj>5443</broj>
        <grad>Beograd</grad>
        <drzava>Srbija</drzava>
      </adresa>
      <brojTelefona tipTelefona='fiksni'>011/521321</brojTelefona>
      <eMail tipEmail='sluzbeni'>kompanija1@mail.com</eMail>
      <eMail tipEmail='sluzbeni'>kompanija2@speedy.com</eMail>
      <eMail tipEmail='sluzbeni'>kompanija3@speedy.com</eMail>
    </Kompanija>
    
  </Adresar>
